// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	Uuid        string           `json:"uuid"`
	Name        string           `json:"name"`
	Price       pgtype.Numeric   `json:"price"`
	Description pgtype.Text      `json:"description"`
	Quantity    int32            `json:"quantity"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
