// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (uuid, name, description, price, quantity) VALUES (gen_random_uuid(), $1, $2, $3, $4) RETURNING uuid, name, price, description, quantity, created_at, updated_at
`

type CreateProductParams struct {
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	Quantity    int32          `json:"quantity"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Quantity,
	)
	var i Product
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Price,
		&i.Description,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT uuid, name, price, description, quantity, created_at, updated_at FROM products
WHERE uuid = $1 LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, uuid string) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, uuid)
	var i Product
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Price,
		&i.Description,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT uuid, name, price, description, quantity, created_at, updated_at FROM products
ORDER BY name
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Price,
			&i.Description,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
